### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by teintuc** [gfcwfzkm/SMRTXE_Project#1]
Hi,

First, great job.
I  flashed your example code but the screen stay blank. I can't get around the problem.
Any ideas?

Thanks

**Comment by teintuc** [comment]
Hi again,

Was a bad usb cable when uploading the code.  Working ok now.
Closing the issue.

Thanks

**Comment by gfcwfzkm** [comment]
Ah good. I was about to test if I can reproduce the error.
Closing the issue.
